#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FieldService.Resource", IsApplication=true)]

namespace FieldService
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int name = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050012
			public const int CDsNum = 2131034130;
			
			// aapt resource value: 0x7f050007
			public const int GPSstatus = 2131034119;
			
			// aapt resource value: 0x7f050013
			public const int PamphletsNum = 2131034131;
			
			// aapt resource value: 0x7f050011
			public const int PensNum = 2131034129;
			
			// aapt resource value: 0x7f050004
			public const int cdsInput = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int cds_button = 2131034121;
			
			// aapt resource value: 0x7f05000e
			public const int enter_button = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int extra_button = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int imageView1 = 2131034128;
			
			// aapt resource value: 0x7f05000d
			public const int item_location = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int item_title = 2131034124;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout2 = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int pamphletsInput = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int pamphlets_button = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int pensInput = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int pens_button = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int summit = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int view_button = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EnterData = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ExtraView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ItemView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int View = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
